//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActPro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActPro.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво е ActPro?.
        /// </summary>
        public static string AboutBadge {
            get {
                return ResourceManager.GetString("AboutBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActPro е иновативна платформа, която свързва ентусиастите със спортните бази. Нашата мисия е да премахнем бариерите пред спорта, като ви дадем достъп до стотици обекти само с няколко клика..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоят дигитален асистент за активен живот.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на акаунт - ActPro.
        /// </summary>
        public static string AccountApproved {
            get {
                return ResourceManager.GetString("AccountApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на акаунт - ActPro.
        /// </summary>
        public static string AccountEmailApprovel {
            get {
                return ResourceManager.GetString("AccountEmailApprovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят обнови профилните си данни..
        /// </summary>
        public static string AccountInfoUpadate {
            get {
                return ResourceManager.GetString("AccountInfoUpadate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавена роля.
        /// </summary>
        public static string AddedRole {
            get {
                return ResourceManager.GetString("AddedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавено в любими!.
        /// </summary>
        public static string AddedToFavorites {
            get {
                return ResourceManager.GetString("AddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа букви, цифри и символи ““,.- №..
        /// </summary>
        public static string AddressNotValid {
            get {
                return ResourceManager.GetString("AddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторските права бяха променени..
        /// </summary>
        public static string AdminRuleChanged {
            get {
                return ResourceManager.GetString("AdminRuleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трябва да приемете общите условия..
        /// </summary>
        public static string AgreeWithTerms {
            get {
                return ResourceManager.GetString("AgreeWithTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрен обект.
        /// </summary>
        public static string ApprovedPlace {
            get {
                return ResourceManager.GetString("ApprovedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокиран и изтрит.
        /// </summary>
        public static string BAN {
            get {
                return ResourceManager.GetString("BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпност от всяко устройство.
        /// </summary>
        public static string BenefitAccessibility {
            get {
                return ResourceManager.GetString("BenefitAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ползи.
        /// </summary>
        public static string BenefitsBadge {
            get {
                return ResourceManager.GetString("BenefitsBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравете за десетките телефонни обаждания, за да разберете дали тенис кортът е свободен. С нас пестите време и нерви:.
        /// </summary>
        public static string BenefitsDescription {
            get {
                return ResourceManager.GetString("BenefitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурност на плащанията.
        /// </summary>
        public static string BenefitSecurity {
            get {
                return ResourceManager.GetString("BenefitSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бързина при резервация.
        /// </summary>
        public static string BenefitSpeed {
            get {
                return ResourceManager.GetString("BenefitSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С какво ви помагаме?.
        /// </summary>
        public static string BenefitsTitle {
            get {
                return ResourceManager.GetString("BenefitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно отказана..
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можете да откажете изминала резервация..
        /// </summary>
        public static string CannotCancelPastReservation {
            get {
                return ResourceManager.GetString("CannotCancelPastReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярни категории.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарът е добавен успешно..
        /// </summary>
        public static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарът е изтрит успешно..
        /// </summary>
        public static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трябва да потвърдите имейла си, преди да добавите коментар!.
        /// </summary>
        public static string CommentNeedApproval {
            get {
                return ResourceManager.GetString("CommentNeedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарът не е намерен..
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарът е обновен успешно..
        /// </summary>
        public static string CommentUpdated {
            get {
                return ResourceManager.GetString("CommentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата за потвърждение е задължителна!.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаден обект.
        /// </summary>
        public static string CreatedPlace {
            get {
                return ResourceManager.GetString("CreatedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущата парола е задължителна!.
        /// </summary>
        public static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датите бяха заключени успешно..
        /// </summary>
        public static string DateClosedSuccessfully {
            get {
                return ResourceManager.GetString("DateClosedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайната дата не може да бъде преди началната..
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датата беше отключена успешно..
        /// </summary>
        public static string DateOpenedSuccessfully {
            get {
                return ResourceManager.GetString("DateOpenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна неочаквана грешка..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрит обект.
        /// </summary>
        public static string DeletedPlace {
            get {
                return ResourceManager.GetString("DeletedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрита резервация на.
        /// </summary>
        public static string DeletedReservation {
            get {
                return ResourceManager.GetString("DeletedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, опишете вашия проблем или въпрос подробно..
        /// </summary>
        public static string DescribeYourIssue {
            get {
                return ResourceManager.GetString("DescribeYourIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете валиден имейл адрес..
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акаунтът вече е потвърден или не съществува..
        /// </summary>
        public static string EmailAlreadyApproved {
            get {
                return ResourceManager.GetString("EmailAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът ви беше потвърден успешно! Вече можете да правите резервации..
        /// </summary>
        public static string EmailApprovedSuccess {
            get {
                return ResourceManager.GetString("EmailApprovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този имейл адрес е блокиран..
        /// </summary>
        public static string EmailIsBanned {
            get {
                return ResourceManager.GetString("EmailIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлa е задължителен!.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете имейл адрес..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете вашето име..
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при създаване, проверете въведените данни!.
        /// </summary>
        public static string ErrorWhileCreatingCheckData {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingCheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при запис: .
        /// </summary>
        public static string ErrorWhileTryingToFill {
            get {
                return ResourceManager.GetString("ErrorWhileTryingToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпно от всякакъв вид устройство.
        /// </summary>
        public static string FeatureAllDevices {
            get {
                return ResourceManager.GetString("FeatureAllDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервации в реално време.
        /// </summary>
        public static string FeatureRealTime {
            get {
                return ResourceManager.GetString("FeatureRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голямо разнообразие от спортове.
        /// </summary>
        public static string FeatureVariety {
            get {
                return ResourceManager.GetString("FeatureVariety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, попълнете всички задължителни полета правилно..
        /// </summary>
        public static string FillInAllFields {
            get {
                return ResourceManager.GetString("FillInAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довиждане! Надяваме се да ви видим отново скоро..
        /// </summary>
        public static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часът вече е минал..
        /// </summary>
        public static string HourAlreadyPassed {
            get {
                return ResourceManager.GetString("HourAlreadyPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този час току-що беше зает!.
        /// </summary>
        public static string HourAlreadyReserved {
            get {
                return ResourceManager.GetString("HourAlreadyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден час..
        /// </summary>
        public static string InvalidHour {
            get {
                return ResourceManager.GetString("InvalidHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна парола. Паролата трябва да е изписана на латиница, да съдържа поне 6 символа,\nот които поне една цифра, една главна и една малка буква,\nкакто и поне един специален символ..
        /// </summary>
        public static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете валиден телефонен номер..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието трябва да е поне 10 символа..
        /// </summary>
        public static string IssueLenght {
            get {
                return ResourceManager.GetString("IssueLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички предложения.
        /// </summary>
        public static string JsAllSuggestions {
            get {
                return ResourceManager.GetString("JsAllSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Известни локации.
        /// </summary>
        public static string JsFamousLocations {
            get {
                return ResourceManager.GetString("JsFamousLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярни активности.
        /// </summary>
        public static string JsPopularActivities {
            get {
                return ResourceManager.GetString("JsPopularActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете валидна активност!.
        /// </summary>
        public static string JsToastSelectActivity {
            get {
                return ResourceManager.GetString("JsToastSelectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете град от предложенията!.
        /// </summary>
        public static string JsToastSelectCity {
            get {
                return ResourceManager.GetString("JsToastSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво ще спортувате?.
        /// </summary>
        public static string LabelActivity {
            get {
                return ResourceManager.GetString("LabelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населено място.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилията е задължителнa!.
        /// </summary>
        public static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа букви и цифри.
        /// </summary>
        public static string LettersNumbersAllowed {
            get {
                return ResourceManager.GetString("LettersNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа латински букви и цифри.
        /// </summary>
        public static string LettersNumbersEnglAllowed {
            get {
                return ResourceManager.GetString("LettersNumbersEnglAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЪЧНА.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече сте оставили максималния брой коментари (3) за този обект..
        /// </summary>
        public static string MaximumComments {
            get {
                return ResourceManager.GetString("MaximumComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да направим спорта достъпен за всеки българин чрез модерни технологии..
        /// </summary>
        public static string MissionDesc {
            get {
                return ResourceManager.GetString("MissionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мисия.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името е задължително!.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новата парола е задължителна!.
        /// </summary>
        public static string NewPasswordIsRequired {
            get {
                return ResourceManager.GetString("NewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрита новина с ID:.
        /// </summary>
        public static string NewsDeleted {
            get {
                return ResourceManager.GetString("NewsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новината е изтрита успешно!.
        /// </summary>
        public static string NewsDeletedSuccessfully {
            get {
                return ResourceManager.GetString("NewsDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикувана е нова новина:.
        /// </summary>
        public static string NewsIsPublished {
            get {
                return ResourceManager.GetString("NewsIsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новината е публикувана успешно!.
        /// </summary>
        public static string NewsIsPublishedSuccessfully {
            get {
                return ResourceManager.GetString("NewsIsPublishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов потребител се регистрира.
        /// </summary>
        public static string NewUserRegistered {
            get {
                return ResourceManager.GetString("NewUserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма дейност.
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма град.
        /// </summary>
        public static string NoCities {
            get {
                return ResourceManager.GetString("NoCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма обект.
        /// </summary>
        public static string NoPlace {
            get {
                return ResourceManager.GetString("NoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е намерен..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна парола! Моля проверете отново!.
        /// </summary>
        public static string NotValidPassword {
            get {
                return ResourceManager.GetString("NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обекта.
        /// </summary>
        public static string ObjectsCountSuffix {
            get {
                return ResourceManager.GetString("ObjectsCountSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа само десетични числа..
        /// </summary>
        public static string OnlyDecimalNumbersAllowed {
            get {
                return ResourceManager.GetString("OnlyDecimalNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа само букви..
        /// </summary>
        public static string OnlyLettersAllowed {
            get {
                return ResourceManager.GetString("OnlyLettersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето може да съдържа само цифри..
        /// </summary>
        public static string OnlyNumbersAllowed {
            get {
                return ResourceManager.GetString("OnlyNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собственик блокира час за.
        /// </summary>
        public static string OwnerManualReservation {
            get {
                return ResourceManager.GetString("OwnerManualReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай го.
        /// </summary>
        public static string OwnerRegisterBtn {
            get {
                return ResourceManager.GetString("OwnerRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правата на собственика бяха променени..
        /// </summary>
        public static string OwnerRuleChanged {
            get {
                return ResourceManager.GetString("OwnerRuleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стани част от нашата мрежа в три лесни стъпки и увеличи клиентите си..
        /// </summary>
        public static string OwnerSubtitle {
            get {
                return ResourceManager.GetString("OwnerSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имаш спортен обект?.
        /// </summary>
        public static string OwnerTitle {
            get {
                return ResourceManager.GetString("OwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна!.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролите трябва да съвпадат..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата беше успешно променена! Можете да влезете с новата си парола..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е минимум {0} символа..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е променена успешно!.
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер е задължителен!.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обектa.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обектът беше създаден успешно..
        /// </summary>
        public static string PlaceAddedSuccessfully {
            get {
                return ResourceManager.GetString("PlaceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обектът беше одобрен успешно..
        /// </summary>
        public static string PlaceApprovedSuccessfully {
            get {
                return ResourceManager.GetString("PlaceApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заключен период от.
        /// </summary>
        public static string PlaceClosed {
            get {
                return ResourceManager.GetString("PlaceClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обектът и всички свързани данни бяха изтрити..
        /// </summary>
        public static string PlaceDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PlaceDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери или въведи активност.
        /// </summary>
        public static string PlaceholderActivity {
            get {
                return ResourceManager.GetString("PlaceholderActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери или въведи град.
        /// </summary>
        public static string PlaceholderCity {
            get {
                return ResourceManager.GetString("PlaceholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за обект с ID.
        /// </summary>
        public static string PlaceId {
            get {
                return ResourceManager.GetString("PlaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обектът е затворен за резервации на тази дата поради.
        /// </summary>
        public static string PlaceIsClosedOnThisDate {
            get {
                return ResourceManager.GetString("PlaceIsClosedOnThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен дата.
        /// </summary>
        public static string PlaceOpened {
            get {
                return ResourceManager.GetString("PlaceOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно редактирахте данните на обекта..
        /// </summary>
        public static string PlaceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PlaceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to планирана профилактика.
        /// </summary>
        public static string PlanedManufacture {
            get {
                return ResourceManager.GetString("PlanedManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече няма нужда да търсите контакти по форуми – всичко е на едно място..
        /// </summary>
        public static string ProbInfoDesc {
            get {
                return ResourceManager.GetString("ProbInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липса на информация.
        /// </summary>
        public static string ProbInfoTitle {
            get {
                return ResourceManager.GetString("ProbInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече можете да изразите вашето мнение относно дадения обект, който сте посетили..
        /// </summary>
        public static string ProbReviewDesc {
            get {
                return ResourceManager.GetString("ProbReviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възможността за отзив.
        /// </summary>
        public static string ProbReviewTitle {
            get {
                return ResourceManager.GetString("ProbReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виждате само свободните часове, актуализирани в реално време..
        /// </summary>
        public static string ProbScheduleDesc {
            get {
                return ResourceManager.GetString("ProbScheduleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактуални графици.
        /// </summary>
        public static string ProbScheduleTitle {
            get {
                return ResourceManager.GetString("ProbScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви не е потвърден. Моля, потвърдете имейла си, за да можете да добавяте обекти..
        /// </summary>
        public static string ProfileNotApprovedForCreatingPlace {
            get {
                return ResourceManager.GetString("ProfileNotApprovedForCreatingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля потвърдете, че не сте робот..
        /// </summary>
        public static string ProveYouAreNotRobot {
            get {
                return ResourceManager.GetString("ProveYouAreNotRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг: ⭐.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахнато от любими!.
        /// </summary>
        public static string RemovedFromFavorites {
            get {
                return ResourceManager.GetString("RemovedFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахната роля.
        /// </summary>
        public static string RemovedRole {
            get {
                return ResourceManager.GetString("RemovedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата заявка е изпратена успешно!.
        /// </summary>
        public static string RequestSentSuccessfully {
            get {
                return ResourceManager.GetString("RequestSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервацията беше одобрена!.
        /// </summary>
        public static string ReservationApproved {
            get {
                return ResourceManager.GetString("ReservationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часът беше блокиран успешно!.
        /// </summary>
        public static string ReservationBlocked {
            get {
                return ResourceManager.GetString("ReservationBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервацията беше анулирана успешно!.
        /// </summary>
        public static string ReservationClosed {
            get {
                return ResourceManager.GetString("ReservationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трябва да потвърдите имейла си, преди да направите резервация!.
        /// </summary>
        public static string ReservationNeedApproval {
            get {
                return ResourceManager.GetString("ReservationNeedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервацията не е намерена..
        /// </summary>
        public static string ReservationNotFound {
            get {
                return ResourceManager.GetString("ReservationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часът беше променен успешно!.
        /// </summary>
        public static string ReservationTimeEdited {
            get {
                return ResourceManager.GetString("ReservationTimeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променен час за.
        /// </summary>
        public static string ReservationUpdate {
            get {
                return ResourceManager.GetString("ReservationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не съществува такава роля..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЪРСИ.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лесно, бързо и удобно резервиране по всяко време..
        /// </summary>
        public static string SearchHeroSubtitle {
            get {
                return ResourceManager.GetString("SearchHeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намери своето място за спорт.
        /// </summary>
        public static string SearchHeroTitle {
            get {
                return ResourceManager.GetString("SearchHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решения.
        /// </summary>
        public static string SolutionsBadge {
            get {
                return ResourceManager.GetString("SolutionsBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемите, които решаваме.
        /// </summary>
        public static string SolutionsTitle {
            get {
                return ResourceManager.GetString("SolutionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баскетбол.
        /// </summary>
        public static string SportBasketball {
            get {
                return ResourceManager.GetString("SportBasketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фитнес.
        /// </summary>
        public static string SportFitness {
            get {
                return ResourceManager.GetString("SportFitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Футбол.
        /// </summary>
        public static string SportFootball {
            get {
                return ResourceManager.GetString("SportFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спортен обект.
        /// </summary>
        public static string SportPlace {
            get {
                return ResourceManager.GetString("SportPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плуване.
        /// </summary>
        public static string SportSwimming {
            get {
                return ResourceManager.GetString("SportSwimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тенис.
        /// </summary>
        public static string SportTennis {
            get {
                return ResourceManager.GetString("SportTennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волейбол.
        /// </summary>
        public static string SportVolleyball {
            get {
                return ResourceManager.GetString("SportVolleyball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай своя бизнес..
        /// </summary>
        public static string Step1Desc {
            get {
                return ResourceManager.GetString("Step1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване.
        /// </summary>
        public static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставяне на документи за собственост..
        /// </summary>
        public static string Step2Desc {
            get {
                return ResourceManager.GetString("Step2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване.
        /// </summary>
        public static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемай резервации онлайн..
        /// </summary>
        public static string Step3Desc {
            get {
                return ResourceManager.GetString("Step3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печели.
        /// </summary>
        public static string Step3Title {
            get {
                return ResourceManager.GetString("Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ние не просто правим софтуер. Ние градим общност, където здравето и спортът са приоритет за всеки..
        /// </summary>
        public static string StorySubtitle {
            get {
                return ResourceManager.GetString("StorySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашата история и цел.
        /// </summary>
        public static string StoryTitle {
            get {
                return ResourceManager.GetString("StoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът бе изтрит! До нови срещи..
        /// </summary>
        public static string SuccessfulDeletedAccount {
            get {
                return ResourceManager.GetString("SuccessfulDeletedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервацията е успешно направена..
        /// </summary>
        public static string SuccessfullReservation {
            get {
                return ResourceManager.GetString("SuccessfullReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно запазихте промените.
        /// </summary>
        public static string SuccessfulSaveChanges {
            get {
                return ResourceManager.GetString("SuccessfulSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно редактирахте данните на потребителя.
        /// </summary>
        public static string SuccessfulUserEdit {
            get {
                return ResourceManager.GetString("SuccessfulUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацията е успешна! Добре дошли..
        /// </summary>
        public static string SuccsessfullRegistration {
            get {
                return ResourceManager.GetString("SuccsessfullRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата заявка беше изпратена успешно! Проверете имейла си за потвърждение..
        /// </summary>
        public static string TicketSendSuccessfully {
            get {
                return ResourceManager.GetString("TicketSendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ обекти с най-висок рейтинг.
        /// </summary>
        public static string TopPlacesTitle {
            get {
                return ResourceManager.GetString("TopPlacesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oбновенo..
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променени данни за.
        /// </summary>
        public static string UpdatedPlace {
            get {
                return ResourceManager.GetString("UpdatedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акаунтът ви е блокиран..
        /// </summary>
        public static string UserAccountIsBanned {
            get {
                return ResourceManager.GetString("UserAccountIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят беше блокиран и изтрит успешно..
        /// </summary>
        public static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят изтри профила си.
        /// </summary>
        public static string UserDeleteAccountSuccess {
            get {
                return ResourceManager.GetString("UserDeleteAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят изтри коментар..
        /// </summary>
        public static string UserDeletedComment {
            get {
                return ResourceManager.GetString("UserDeletedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят отказа резервация..
        /// </summary>
        public static string UserDeletedReservation {
            get {
                return ResourceManager.GetString("UserDeletedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят не съществува в системата!.
        /// </summary>
        public static string UserIsNotRegistered {
            get {
                return ResourceManager.GetString("UserIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят влезе в системата..
        /// </summary>
        public static string UserLoggedInSuccessfully {
            get {
                return ResourceManager.GetString("UserLoggedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят добави коментар..
        /// </summary>
        public static string UserMadeComment {
            get {
                return ResourceManager.GetString("UserMadeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят направи резервация..
        /// </summary>
        public static string UserMadeReservation {
            get {
                return ResourceManager.GetString("UserMadeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят смени паролата си успешно..
        /// </summary>
        public static string UserUpdatePasswordSuccess {
            get {
                return ResourceManager.GetString("UserUpdatePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребител с този имейл вече съществува..
        /// </summary>
        public static string UserWithThisEmailExists {
            get {
                return ResourceManager.GetString("UserWithThisEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете вид спорт!.
        /// </summary>
        public static string ValidationActivityRequired {
            get {
                return ResourceManager.GetString("ValidationActivityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете адрес!.
        /// </summary>
        public static string ValidationAddressRequired {
            get {
                return ResourceManager.GetString("ValidationAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капацитетът трябва да е между 1 и 1000 души!.
        /// </summary>
        public static string ValidationCapacityRange {
            get {
                return ResourceManager.GetString("ValidationCapacityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете капацитет!.
        /// </summary>
        public static string ValidationCapacityRequired {
            get {
                return ResourceManager.GetString("ValidationCapacityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете населено място!.
        /// </summary>
        public static string ValidationCityRequired {
            get {
                return ResourceManager.GetString("ValidationCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете описание!.
        /// </summary>
        public static string ValidationDescriptionRequired {
            get {
                return ResourceManager.GetString("ValidationDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието трябва да е между 10 и 2000 символа..
        /// </summary>
        public static string ValidationDescriptionTooLong {
            get {
                return ResourceManager.GetString("ValidationDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете име на обекта!.
        /// </summary>
        public static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името е твърде дълго! Максимум 200 символа..
        /// </summary>
        public static string ValidationNameTooLong {
            get {
                return ResourceManager.GetString("ValidationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цената трябва да е между 0.01 и 9999 лв.!.
        /// </summary>
        public static string ValidationPriceRange {
            get {
                return ResourceManager.GetString("ValidationPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете цена!.
        /// </summary>
        public static string ValidationPriceRequired {
            get {
                return ResourceManager.GetString("ValidationPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете тип!.
        /// </summary>
        public static string ValidationTypeRequired {
            get {
                return ResourceManager.GetString("ValidationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако имейлът съществува, сме изпратили линк за възстановяване..
        /// </summary>
        public static string ValidEmailAddress {
            get {
                return ResourceManager.GetString("ValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачност, иновация и непоколебима подкрепа за местния бизнес и спортни клубове..
        /// </summary>
        public static string ValuesDesc {
            get {
                return ResourceManager.GetString("ValuesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ценности.
        /// </summary>
        public static string ValuesTitle {
            get {
                return ResourceManager.GetString("ValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виж детайли.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виж повече.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-голямата екосистема за активен отдих и управление на спортни бази в страната..
        /// </summary>
        public static string VisionDesc {
            get {
                return ResourceManager.GetString("VisionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визия.
        /// </summary>
        public static string VisionTitle {
            get {
                return ResourceManager.GetString("VisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли в ActPro!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешен имейл.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въвели сте грешна парола..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
